ui/forms.py
ui/settings.py
users/views.py

@danielquinn This takes care of most of the security issues. We should check the cookie https settings don't break anything in staging. I want to check with Mateusz before enabling HSTS. Also ideally this would have some unit tests!
Also please ignore previous PR which was against master, not develop.

fix some minor security issues

---

ui/settings.py
ui/templates/ui/base.html
ui/templates/ui/index.html
wins/forms.py
wins/templates/wins/new-field.html
wins/templates/wins/new.html

@danielquinn and here is the corresponding UI stuff. LMK if you want me to quickly talk you through.

More form tweaks

---

ui/settings.py
wins/templates/wins/confirmation.html
wins/templates/wins/thanks.html
wins/views.py

With the exception of the bootstrappy hacks I put in there to align the stars in smaller resolutions, there's nothing much to see here.

Last minute changes

---

wins/forms.py
wins/templates/wins/partials/win-form.html

Validation for win date and values

---

requirements.txt
ui/settings.py
ui/templates/ui/admin/csv-upload.html
ui/templates/ui/admin/form.html
ui/templates/ui/admin/index.html
ui/urls.py
ui/views.py

this allows the admin user to upload csv files to s3 and tell mi backend
about that.
This allows MI to later present these files back to users for download.
Here are the env vars needed for this to work:
CSV_UPLOAD_AWS_ACCESS_KEY_ID
CSV_UPLOAD_AWS_SECRET_ACCESS_KEY
CSV_UPLOAD_AWS_BUCKET
CSV_AWS_REGION

DO NOT MERGE: Add csv upload support

---

ui/views.py

IE sends csvs as text/plain instead of text/csv so this changes the
check to handle that scenario

Handle Mime type that IE uses

---

requirements.txt
ui/views.py

This allows us to see what's going wrong when users try to upload files

Improve logging in csvfile uploads

---

ui/views.py

this commit allows uploads from IE on Windows 7

Windows 7 uses microsoft mime type

---

ui/settings.py

Backend has changed endpoint format and has dedicated app for csv now.

change settings to update endpoint change in the backend

---

alice/helpers.py
ui/views.py

This updates the CSV view to stream the CSV file from the backend and
updates the alice client to support streaming responses

Adds streaming file support for Alice

---

.env.template
.envrc
README.md

I've tweaked the .envrc to be more generic as it was throwing an error as I don't have virtaulenv. I have also made it read a .env file if present.
I have added .env.template to show what a .env file should contain to get the app running
I have tweaked the README to include how to setup Python as it might be used by a non Python dev, and I've included some bits I thought were missing

Update README, add template for .env and update .envrc

---

wins/forms.py
wins/templates/wins/partials/win-form.html
wins/templates/wins/win-details.html

This also makes setting at least one associated programme as required.

Increase number of associated programmes

---

wins/forms.py
wins/templates/wins/partials/win-form.html

Fixing blank item in marketing source
skipping blank choice that is a byproduct of the process

Mi 1458 skipping blank choice that is a byproduct of the process

---

.gitignore
Dockerfile
pytest.ini
requirements.txt
runtime.txt

This is a range of dependency updates. Relevant change logs:
https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md
https://docs.djangoproject.com/en/1.11/releases/1.11.12/
https://docs.djangoproject.com/en/1.11/releases/1.11.13/
https://github.com/requests/requests/blob/master/HISTORY.rst
https://github.com/getsentry/raven-python/blob/master/CHANGELOG.md
Also removes pytest-related packages from the requirements as they weren't being used.
Also updates Python to 3.6.5 and adds the static files directory to .gitignore.
Will do another PR to update the rest of the requirements.

Update various dependencies

---

runtime.txt

updating python runtime to 3.7.8

updating python runtime to 3.7.8

---

package-lock.json

This is a fix for the y18n vulnerability that appeared yesterday.

Resolve y18n vulnerability

---

package-lock.json
package.json

Fixing the `set-value` vulnerability

Fix set-value vulnerability

---

.env.template
Makefile
README.md

This PR updates instructions for running the app and adds a Makefile to make local setup easier.

Update README and add Makefile

---

package-lock.json
package.json
requirements.txt

This week's Dependabot updates

Dependabot (2022-11-07)

---

requirements.txt

Dependabot dependancies 2022-11-21

---

requirements.txt

Reverts uktrade/export-wins-ui#540

Revert "Chore dependencies 2022 11 28"

---

ui/static/ui/css/main_2018-04-29.css
ui/templates/ui/base.html

Include accessibility statement and privacy policy in Export Wins footer.
My linter fixed the linting issues on these files so it's hard to see the differences but the additions are:
`ui/templates/ui/base.html` line 86-115
`ui/static/ui/css/main_2018-04-29.css` line 589-603

Add policies in footer

---

ui/static/ui/css/main_2023-01-23.css
ui/templates/ui/base.html

The CSS for the policies in the footer hasn't been picked up. This PR tries to fix that

Fix CSS for Policies in the footer

---

requirements.txt

Bump Django to 3.2.18 to fix a vulnerability

Bump Django to 3.2.18

---

.github/dependabot.yml
package-lock.json
package.json

Reverts uktrade/export-wins-ui#583
The breaking `sass` upgrade was inadvertantely merged in again. I have reverted this and have added it to the Dependabot ignore list so we don't get more PRs for it

Revert "Chore/dependencies 2023 03 20"

---

requirements.txt

There is a vulnerability in the `requests` dependency.

Update requests dependency

---

requirements.txt

Bump django to 3.2.23

---

wins/templates/wins/partials/win-form.html

Scope of this PR:
Introduce a static and collapsable component with information around oil and gas sector

Add Oil and Gas helper component for export wins form

---

requirements.txt

Bump Django to 3.2.25 as there is a vulnerability

Bump Django to 3.2.25

---

package-lock.json
ui/templates/ui/base.html

Added a banner about moving to Data Hub

Added a banner about moving to Data Hub
